In [1]:
import numpy as np
Random=np.random.random((5,3))
print(Random)

[[0.32325616 0.18515716 0.07845358]
 [0.62123767 0.40439016 0.11112973]
 [0.98588643 0.8849145  0.09223634]
 [0.24746391 0.3112075  0.17860995]
 [0.94412364 0.09575294 0.72470261]]


In [2]:
zeros=np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
range=np.arange(5,31,2)
print(range)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [4]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)
print("\nDimension of this array : ",arr.ndim)
print("\nDatatype of this array : ",arr.dtype)
print("\nShape of this array : ",arr.shape)
print("\nFlatten array : ",arr.flatten())

[[1 2 3]
 [2 3 4]
 [3 4 5]]

Dimension of this array :  2

Datatype of this array :  int64

Shape of this array :  (3, 3)

Flatten array :  [1 2 3 2 3 4 3 4 5]
