In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
import numpy as np
a=np.array(([1,2,3],[4,5,6]))
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
b=np.shape(a)
print(b)

(2, 3)


In [11]:
import numpy as np
c=a.reshape(3,2)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
import numpy as np
d=np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np
e=np.random.random((2,2))
print(e)

[[0.83143775 0.65975141]
 [0.03010333 0.18723117]]


In [15]:
import numpy as np
f=np.array((([1,2,3],[4,5,6],[7,8,9])))
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
import numpy as np
flat=f.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [36]:
h=np.array((([1,2,3],[4,5,6]),([4,6,7],[7,8,9])))
print("\n no of dimensions:",h.ndim)


 no of dimensions: 3


In [40]:
print(h.shape)

(2, 2, 3)


In [41]:
print(h.dtype)

int64


In [45]:
#to determine the number of array
size=len(a)
print(size)

2


In [3]:
import numpy as np
a=np.array([1,2,3])
n=a.astype('float64')
print(n)
print(n.dtype)

[1. 2. 3.]
float64
