In [11]:
#slicing
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b=a[2:9:2]
c=a[2:6]
print(b)
print(c)

[3 5 7 9]
[3 4 5 6]


In [14]:
#reversing the array
d=a[::-1]
e=a[9:2:-3]
print(d)
print(e)

[9 8 7 6 5 4 3 2 1]
[9 6]


In [28]:
#slicing multidimensional aray
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
sarr=arr[0:2,1:3]
print(arr)
print(sarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [31]:
#extracting first column
col=arr[:,0]
print(col)

[1 4 7]


In [32]:
#extracting first row
col2=arr[0,:]
print(col2)

[1 2 3]


In [33]:
#extracting every other rows
col3=arr[0:2:1]
print(col3)

[[1 2 3]
 [4 5 6]]


In [34]:
#array indexing
#single dimensional
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50,])
print(arr[0])
print(arr[4])


10
50


In [50]:
#array indexing
#multidimensional array
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0,0])
print(arr1[2,0])

1
7


In [55]:
#basic indexing
arr2=[10,20,30,40,50]
print(arr2[1])

20


In [56]:
#negative indexing
print(arr2[-1])

50


In [57]:
#slice indexing
print(arr2[1:3])

[20, 30]


In [1]:
#boolean indexing

In [2]:
#horizontal joining
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
#vertical joining
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#depth joining
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
#array splitting
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
#array splitting
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
