In [2]:
#index retrival 
import numpy as np
arr=np.array([1,2,5,3,6,8,5,9])
x=np.where(arr==9)
print(x)

(array([7]),)


In [5]:
#index retrival
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [6]:
#index retrival
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%3==1)
print(x)

(array([0, 3, 5]),)


In [9]:
#index retrival
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='left')
print(x)

5


In [12]:
#index retrival
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,1,side='right')
print(x)

2


In [13]:
#sorting of array
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))


[2 4 5 6 7 9]


In [14]:
#sorting of array
import numpy as np
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [17]:
#boolean indexing
import numpy as np
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]


In [21]:
#filtering
import numpy as np
arr=np.array([31,78,69,100])
filter_arr=arr>60
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True  True  True]
[ 78  69 100]
